services:
    _defaults:
        autowire: true      # Autowiring des dépendances
        autoconfigure: true # Autoconfiguration des services

    # Rendre les classes dans src/ disponibles en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration du service Dompdf
    Dompdf\Dompdf:
        arguments:
            $options: '@Dompdf\Options'  # Injection de l'instance Options dans Dompdf

    Dompdf\Options:  # Définir un service pour les options
        arguments: []  # Ajouter des options si nécessaire
